// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMDSs8Twe_vuC1UVj52dewuQaBFRGebPU',
    appId: '1:250420963396:web:062d000dda30980ca97411',
    messagingSenderId: '250420963396',
    projectId: 'tudv2004',
    authDomain: 'tudv2004.firebaseapp.com',
    storageBucket: 'tudv2004.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBI76C8TzTe3DqnEs3TP-ogpnqzG1RI4Mg',
    appId: '1:250420963396:android:a26c3e50dde908afa97411',
    messagingSenderId: '250420963396',
    projectId: 'tudv2004',
    storageBucket: 'tudv2004.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMDSs8Twe_vuC1UVj52dewuQaBFRGebPU',
    appId: '1:250420963396:web:152852cd625d2a48a97411',
    messagingSenderId: '250420963396',
    projectId: 'tudv2004',
    authDomain: 'tudv2004.firebaseapp.com',
    storageBucket: 'tudv2004.firebasestorage.app',
  );
}
